//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFindTutorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUCTOR
    {
        public int Instructor_ID { get; set; }
        public string Instructor_FirstName { get; set; }
        public string Instructor_LastName { get; set; }
        public byte[] Instructor_Email { get; set; }
        public string Instructor_TelNumber { get; set; }
        public string Instructor_location { get; set; }
        public string Instructor_Pic { get; set; }
        public string Instructor_University { get; set; }
        public byte[] Teaching_History { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string Confirmation { get; set; }
    }
}
